###
# Auth
###

### register new user and get token
POST http://127.0.0.1:8001/register/
Content-Type: application/json

{
  "username": "user1",
  "password": "password"
}

> {% client.global.set("auth_token", response.body.token); %}

### or get token for exists user
POST 127.0.0.1:8001/login/
Content-Type: application/json

{
  "username": "user1",
  "password": "password"
}

> {% client.global.set("auth_token", response.body.token); %}

###
# User Profile
###

### get
GET 127.0.0.1:8001/user/profile/
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### update
PUT 127.0.0.1:8001/user/profile/
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "about": "XDDDD"
}

### delete
DELETE 127.0.0.1:8001/user/profile/
Content-Type: application/json
Authorization: Bearer {{auth_token}}


###
# Post
###

### get all (available query params: page, tag, query, sort[create|title], order[desc|asc])
GET 127.0.0.1:8001/posts/
Content-Type: application/json

### get by slug
GET 127.0.0.1:8001/post/slug/
Content-Type: application/json


###
# Tag
##

### get all
GET 127.0.0.1:8001/tags/
Content-Type: application/json


###
# User Post
###

### create
POST 127.0.0.1:8001/user/post/
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "title": "mu title2",
  "text": "2message text2222xD",
  "tags": [
    {"name": "tag111"},
    {"name": "dadada"}
  ],
  "isPrivate": false
}

> {% client.global.set("post_id", response.body.id); %}

### get all by current user
GET 127.0.0.1:8001/user/posts/
Content-Type: application/json
Authorization: Bearer {{auth_token}}

> {% client.global.set("post_id", response.body.results[0].id); %}

### get by id
GET 127.0.0.1:8001/user/post/{{post_id}}/
Content-Type: application/json
Authorization: Bearer {{auth_token}}

> {% client.global.set("post_id", response.body.id); %}

### update by id
PUT 127.0.0.1:8001/user/post/{{post_id}}/
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "title": "new title",
  "text": "new text",
  "tags": [
    {"name": "tag111"},
    {"name": "tag222"}
  ]
}

### delete all
DELETE 127.0.0.1:8001/user/posts/
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### delete by id
DELETE 127.0.0.1:8001/user/post/{{post_id}/
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### markdown to html
POST 127.0.0.1:8001/user/post/md2html/
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
    "text": "# asd\n test"
}
